### PR TITLE
Branch anna

### LINKED ISSUE #2: Build Flavor Page
### What
Represents an ice cream flavor and reviews for that flavor.
- [x] Flavor name
- [x] Flavor photo
- [x] Average rating
- [x] Description
- [x] Reviews (review title, username, star rating, date last edited, review content)
- [x] Floating Action Button to add review or edit review if user has already added review
- [x] Dialog to add review that adds review to top of ListView of reviews
- [x] Dialog to edit preexisting review

### Why
This flavor page front-end represents the front-end for user interaction with our tables of reviews for each ice cream brand as well as for the table of ice cream flavors. This user interaction consists of CRUD operations: create review, read review, update review, and add review.

### How
We will use Flutter, especially Material Components.

### PR DESCRIPTION
**Pull request by annazelenka**
Added flavor description above ListView and finished add review/edit review functionality.

Add review/edit review functionality:
* if user hasn't added review before, they can click the floating action button to add a review. A blank review dialog will appear. If they successfully add the review using the dialog (ie the author, title, and content fields are not blank and they click the add review button), it will be added to the top of the list. 
* if user has added a review, they can click the edit button attached to the review that they have written. A review dialog with the current review content will appear. If they successfully edit the review using the dialog (ie the author, title, and content fields are not blank and they click the edit review button), the review will be updated in its current position.
* Note that currently users are limited to adding 1 review per flavor. We can discuss this in a meeting, but my reasoning is that we don't want users to be able to skew a flavor's average rating by submitting multiple reviews. Also, they can always update their review if they change their minds.

* TODO: SQL functionality (CRUD operations on Reviews table) is not set up yet, but the code is set up so that it will be easy to incorporate.
* TODO: Indentation is still a problem. I am looking into VSCode automatic formatting options for Dart and will hopefully fix it by my next pull request.
* TODO: improve the UI by fixing colors, fonts, and formatting bugs.

See [demo](https://imgur.com/a/0bjOw1c).

### CODE REVIEW

**Comment by khalludi** [comment]
Nice. The code looks well-written and is easy to read. 😺

**Review by khalludi — APPROVED** [review]
Didn't see the review button before. The code looks good!

**Review by payalahuja98 — COMMENTED** [review]
Rendering error - some pixels are going off the screen. Possible solution: Container -> Expanded.

**Comment by annazelenka** [comment]
Closing because there were errors. We can use the new pull request (anna_reviews) instead :)

**Pull request closed without merging**
